# Generated by Django 5.0.5 on 2024-05-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_status_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='professor',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='serie',
            field=models.CharField(choices=[('1ANO', '1 ANO'), ('2ANO', '2 ANO'), ('3ANO', '3 ANO'), ('4ANO', '4 ANO'), ('5ANO', '5 ANO'), ('6ANO', '6 ANO'), ('7ANO', '7 ANO'), ('8ANO', '8 ANO'), ('9ANO', '9 ANO'), ('1SERIE', '1 SÉRIE'), ('2SERIE', '2 SÉRIE'), ('3SERIE', '3 SÉRIE')], max_length=30),
        ),
    ]
