# Generated by Django 4.2.11 on 2024-05-07 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_agendamento_professor_alter_agendamento_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.ForeignKey(default='Não Agendado', on_delete=django.db.models.deletion.CASCADE, to='app.status'),
        ),
    ]
